export const family = [
    {
        id:1, 
        name:"Carmen María Morales",
        dob: "21/12/1918 - 05/05/2012",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: [],
        children: ["Elia Rosa Morales",,"Luis Enrique Morales","Ivonne Teresa Morales","Mirna Rosa Morales","Antonio Rafael Morales","Mercedes Epifanía Morales","Jesús Miguel Morales","Alfredo Luis Morales","Yuraima Dolores Morales"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://ih1.redbubble.net/image.685200323.6341/flat,750x1000,075,f.u1.jpg"
    },
    {
        id:2, 
        name:"Elia Rosa Morales", 
        dob: "17/05/1937 ",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:3,
        name:"Luis Enrique Morales",
        dob: "07/10/1939",
        pob: "Cumaná, Venezuela",
        spouse: ["María Strucco Gallozzi","Luz Marina Moreno"],
        parents: ["Carmen María Morales"],
        children: ["Luis Enrique Morales Strucco","Maien Morales Strucco","Juan Manuel Morales Strucco","Leyla Morales Moreno","Leonardo Morales Moreno","Luis Alejandro Morales Moreno"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://wallpapercave.com/wp/wp3875544.png"
    },
    {
        id:4, 
        name:"Ivonne Teresa Morales", 
        dob: "07/03/1943",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/764/205/png-clipart-goku-dragon-ball-z-dokkan-battle-vegeta-arale-norimaki-krillin-goku-baby-computer-wallpaper-fictional-character.png"
    },
    {
        id:5, 
        name:"Mirna Rosa Morales", 
        dob: "03/07/1946 ",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/552/554/png-clipart-goku-baby-vegeta-krillin-saiyan-goku-child-computer-wallpaper.png"
    },
    {
        id:6, 
        name:"Antonio Rafael Morales", 
        dob: "08/12/1948",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://w7.pngwing.com/pngs/690/421/png-transparent-goku-frieza-vegeta-gohan-trunks-goku-computer-wallpaper-trunks-cartoon.png"
    },
    {
        id:7, 
        name:"Mercedes Epifanía Morales", 
        dob: "27/03/1950",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://i.pinimg.com/originals/9b/47/c5/9b47c528e901a4d5e3f4093692b8e39e.jpg"
    },
    {
        id:8, 
        name:"Jesús Miguel Morales", 
        dob: "29/09/1951 - 20/08/2018",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK9rJgc8JjhQKV6E_Kjwy8RQWnmdrfFQjWlh-a3hUGWEoOKXxnncg6x9bogJwrSSoQDbQ&usqp=CAU"
    },
    {
        id:9, 
        name:"Alfredo Luis Morales", 
        dob: "30/03/1954",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://c0.klipartz.com/pngpicture/268/488/gratis-png-goku-gohan-goten-vegeta-chibi-goku.png"
    },
    {
        id:10, 
        name:"Yuraima Dolores Morales", 
        dob: "22/04/1956",
        pob: "Cumaná, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/838/760/png-clipart-goku-dragon-ball-z-gohan-vegeta-super-saiya-goku-manga-chibi.png"
    },
    {
        id:11, 
        name:"Luis Enrique Morales Strucco", 
        dob: "12/05/1964",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Enrique Morales","María Strucco Gallozzi"],
        children: ["Santiago Elías Morales Hernández"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:12, 
        name:"Maien Morales Strucco", 
        dob: "13/12/1965",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Enrique Morales","María Strucco Gallozzi"],
        children: ["Cristina Cabello Morales","Daniel Cabello Morales"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://ih1.redbubble.net/image.685200323.6341/flat,750x1000,075,f.u1.jpg"
    },
    {
        id:13, 
        name:"Juan Manuel Morales Strucco", 
        dob: "20/07/1968",
        pob: "Cumaná, Venezuela",
        spouse: ["Magally Lopez Benavides"],
        parents: ["Luis Enrique Morales","María Strucco Gallozzi"],
        children: ["Rafael Ángel Morales López","Dayana Corina Morales López"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://scontent.fmia1-2.fna.fbcdn.net/v/t1.6435-9/50876773_10217139800062593_8124584141132922880_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=nxPx6qh1DHoAX_GG3Lh&_nc_ht=scontent.fmia1-2.fna&oh=9a244c846ac12f9747c795a61d5f942a&oe=61493C27"
    },
    {
        id:14, 
        name:"Leyla Morales Moreno", 
        dob: "07/08/1973",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Enrique Morales","Luz Marina Moreno"],
        children: ["Valentina Beatriz Lougheed Morales ","Peter James Lougheed Morales"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/764/205/png-clipart-goku-dragon-ball-z-dokkan-battle-vegeta-arale-norimaki-krillin-goku-baby-computer-wallpaper-fictional-character.png"
    },
    {
        id:15, 
        name:"Leonardo Morales Moreno", 
        dob: "18/09/1975",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Enrique Morales","Luz Marina Moreno"],
        children: ["Oriana del Valle Morales Vázquez","Samuel David Morales Vázquez"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://w7.pngwing.com/pngs/690/421/png-transparent-goku-frieza-vegeta-gohan-trunks-goku-computer-wallpaper-trunks-cartoon.png"
    },
    {
        id:16, 
        name:"Luis Alejandro Morales Moreno", 
        dob: "21/07/1978",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Carmen María Morales"],
        children: ["Natalia Alejandra Morales López","Mía Lorraine Morales López"],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK9rJgc8JjhQKV6E_Kjwy8RQWnmdrfFQjWlh-a3hUGWEoOKXxnncg6x9bogJwrSSoQDbQ&usqp=CAU"
    },
    {
        id:17, 
        name:"Santiago Elías Morales Hernández", 
        dob: "14/07/1992",
        pob: "Guri, Venezuela",
        spouse: [],
        parents: ["Luis Enrique Morales Strucco"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/552/554/png-clipart-goku-baby-vegeta-krillin-saiyan-goku-child-computer-wallpaper.png"
    },
    {
        id:18, 
        name:"Cristina Cabello Morales", 
        dob: "16/07/1997",
        pob: "Cancún, México",
        spouse: [],
        parents: ["Maien Morales Strucco"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://wallpapercave.com/wp/wp3875544.png"
    },
    {
        id:19, 
        name:"Daniel Cabello Morales", 
        dob: "14/09/1998",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Maien Morales Strucco"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://ih1.redbubble.net/image.685200323.6341/flat,750x1000,075,f.u1.jpg"
    },
    {
        id:20, 
        name:"Rafael Ángel Morales López", 
        dob: "06/06/1994",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Juan Manuel Morales Strucco","Magally Lopez Benavides"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://scontent.fmia1-2.fna.fbcdn.net/v/t1.6435-9/48090895_10217285377742387_1017029486685716480_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=0debeb&_nc_ohc=LrIv7Sw1vi0AX-RKTmE&_nc_ht=scontent.fmia1-2.fna&oh=ff6e5e80a172137fc8f44bb6e1f720fd&oe=6149F5A7"
    },
    {
        id:21, 
        name:"Dayana Corina Morales López", 
        dob: "25/01/1997",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Juan Manuel Morales Strucco","Magally Lopez Benavides"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://scontent.fmia1-2.fna.fbcdn.net/v/t1.18169-9/12373349_10208345687698655_3481463497666793917_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=174925&_nc_ohc=FTtA895BlQQAX9A75lM&_nc_ht=scontent.fmia1-2.fna&oh=7621e21cb9425839648626f8f8d389a5&oe=614C8B08"
    },
    {
        id:22, 
        name:"Valentina Beatriz Lougheed Morales", 
        dob: "16/06/1998",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Leyla Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://e7.pngegg.com/pngimages/838/760/png-clipart-goku-dragon-ball-z-gohan-vegeta-super-saiya-goku-manga-chibi.png"
    },
    {
        id:23, 
        name:"Peter James Lougheed Morales", 
        dob: "04/07/2005",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Leyla Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:24, 
        name:"Oriana del Valle Morales Vázquez", 
        dob: "12/08/2002",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Leonardo Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://wallpapercave.com/wp/wp3875544.png"
    },
    {
        id:25, 
        name:"Samuel David Morales Vázquez", 
        dob: "12/08/2002",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Leonardo Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://ih1.redbubble.net/image.685200323.6341/flat,750x1000,075,f.u1.jpg"
    },
    {
        id:26, 
        name:"Natalia Alejandra Morales López ", 
        dob: "08/11/2012",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Alejandro Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:27, 
        name:"Mía Lorraine Morales López", 
        dob: "21/09/2014",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: ["Luis Alejandro Morales Moreno"],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:28, 
        name:"María Strucco Gallozzi", 
        dob: "xx/xx/xxxx",
        pob: "Italia",
        spouse: [],
        parents: [],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    },
    {
        id:29, 
        name:"Magally Lopez Benavides", 
        dob: "xx/xx/xxxx",
        pob: "Caracas, Venezuela",
        spouse: [],
        parents: [],
        children: [],
        bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
        image:"https://res.cloudinary.com/teepublic/image/private/s--5E68shFf--/c_crop,x_10,y_10/c_fit,h_830/c_crop,g_north_west,h_1038,w_1038,x_-141,y_-104/l_upload:v1565806151:production:blanks:vdbwo35fw6qtflw9kezw/fl_layer_apply,g_north_west,x_-252,y_-215/b_rgb:ffb81c/c_limit,f_jpg,h_630,q_90,w_630/v1591405243/production/designs/11034957_0.jpg"
    }
]